// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLogLinesByJob = `-- name: CountLogLinesByJob :one
SELECT COUNT(*)::bigint AS count
FROM log_lines
WHERE job_run_id = $1
`

// Total log line count for a job_run. Powers the "(N lines omitted)"
// divider between head and tail in the UI: omitted = total - head -
// tail, clamped to >= 0 (when head+tail overlap or exceed total,
// callers dedupe and zero the omitted count). Cheap row count
// against the same (job_run_id, seq) index TailLogLinesByJob hits.
func (q *Queries) CountLogLinesByJob(ctx context.Context, jobRunID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLogLinesByJob, jobRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, description, config_path, created_at, updated_at
FROM projects
WHERE slug = $1
LIMIT 1
`

type GetProjectBySlugRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Description *string
	ConfigPath  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i GetProjectBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ConfigPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunWithPipeline = `-- name: GetRunWithPipeline :one
SELECT r.id, r.pipeline_id, pl.name AS pipeline_name,
       p.id AS project_id, p.slug AS project_slug,
       p.check_reporting_mode,
       r.counter, r.cause, r.cause_detail, r.status, r.queue_reason,
       r.cancel_reason, r.superseded_by, r.revisions,
       r.has_services, r.service_names,
       r.created_at, r.started_at, r.finished_at, r.triggered_by,
       COALESCE(NULLIF(r.definition, '{}'::jsonb), pl.definition) AS pipeline_definition,
       (r.definition <> '{}'::jsonb) AS has_run_snapshot
FROM runs r
JOIN pipelines pl ON pl.id = r.pipeline_id
JOIN projects p ON p.id = pl.project_id
WHERE r.id = $1
LIMIT 1
`

type GetRunWithPipelineRow struct {
	ID                 pgtype.UUID
	PipelineID         pgtype.UUID
	PipelineName       string
	ProjectID          pgtype.UUID
	ProjectSlug        string
	CheckReportingMode string
	Counter            int64
	Cause              string
	CauseDetail        []byte
	Status             string
	QueueReason        *string
	CancelReason       *string
	SupersededBy       pgtype.UUID
	Revisions          []byte
	HasServices        bool
	ServiceNames       []string
	CreatedAt          pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
	TriggeredBy        *string
	PipelineDefinition []byte
	HasRunSnapshot     bool
}

// pl.definition is returned so the read path can decode the
// notifications array and stamp on/uses onto synth job rows
// without a second round-trip. Adds one JSONB column to the
// response but avoids a per-run "did this pipeline have
// notifications?" lookup.
// pipeline_definition is the run's IMMUTABLE SNAPSHOT (runs.definition,
// migration 00067) when present, else the live pl.definition — ONE JSONB, not
// two, so a poll never transfers/deserialises both. has_run_snapshot flags which
// it is: true → the read path can compute a gate's freeze-hold state (#227) from
// this same snapshot (the exact def the approve/expiry paths block on); false
// (an orphaned '{}' snapshot) → it fell back to the live def, so Notifications
// still render but no freeze annotation runs. project_id feeds the freeze lookup.
func (q *Queries) GetRunWithPipeline(ctx context.Context, id pgtype.UUID) (GetRunWithPipelineRow, error) {
	row := q.db.QueryRow(ctx, getRunWithPipeline, id)
	var i GetRunWithPipelineRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.PipelineName,
		&i.ProjectID,
		&i.ProjectSlug,
		&i.CheckReportingMode,
		&i.Counter,
		&i.Cause,
		&i.CauseDetail,
		&i.Status,
		&i.QueueReason,
		&i.CancelReason,
		&i.SupersededBy,
		&i.Revisions,
		&i.HasServices,
		&i.ServiceNames,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TriggeredBy,
		&i.PipelineDefinition,
		&i.HasRunSnapshot,
	)
	return i, err
}

const headLogLinesByJob = `-- name: HeadLogLinesByJob :many
SELECT seq, stream, at, text
FROM log_lines
WHERE job_run_id = $1
ORDER BY seq
LIMIT $2
`

type HeadLogLinesByJobParams struct {
	JobRunID pgtype.UUID
	Limit    int32
}

type HeadLogLinesByJobRow struct {
	Seq    int64
	Stream string
	At     pgtype.Timestamptz
	Text   string
}

// Returns the head (first $2 lines) of a job's logs in seq order.
// Used together with TailLogLinesByJob to render the run detail's
// log view as "first N + last M lines" — the verbose middle of
// long jobs (Gradle test execution, kafka chatter) is rarely what
// operators need first; the START (Gradle daemon setup, dependency
// resolution from Nexus, classpath assembly) and the END (failure
// + stack trace) are. Pre-v0.14.7 the cap-on-tail meant a 23k-line
// job hid the entire startup; `kubectl logs` was the workaround.
func (q *Queries) HeadLogLinesByJob(ctx context.Context, arg HeadLogLinesByJobParams) ([]HeadLogLinesByJobRow, error) {
	rows, err := q.db.Query(ctx, headLogLinesByJob, arg.JobRunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeadLogLinesByJobRow{}
	for rows.Next() {
		var i HeadLogLinesByJobRow
		if err := rows.Scan(
			&i.Seq,
			&i.Stream,
			&i.At,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestRunMetaByProjectSlug = `-- name: LatestRunMetaByProjectSlug :many
WITH latest AS (
    SELECT DISTINCT ON (r.pipeline_id)
        r.pipeline_id, r.id AS run_id, r.revisions, r.triggered_by,
        r.cause, r.cause_detail
    FROM runs r
    JOIN pipelines pl ON pl.id = r.pipeline_id
    JOIN projects p ON p.id = pl.project_id
    WHERE p.slug = $1
    ORDER BY r.pipeline_id, r.created_at DESC
),
expanded AS (
    SELECT l.pipeline_id,
           l.triggered_by,
           l.cause,
           -- Guard the JSON→int cast: only accept 1-9 digits so a
           -- malformed cause_detail (pr_number = "abc", a negative, or
           -- a value past int32) can't 500 the cards. 9 digits caps at
           -- 999,999,999 < int32 max; anything else falls back to 0.
           (CASE
               WHEN l.cause_detail->>'pr_number' ~ '^[0-9]{1,9}$'
               THEN (l.cause_detail->>'pr_number')::int
               ELSE 0
           END)::int AS pr_number,
           (key)::uuid AS material_id,
           (value->>'revision')::text AS revision,
           (value->>'branch')::text AS branch
    FROM latest l, jsonb_each(l.revisions)
),
joined AS (
    SELECT DISTINCT ON (e.pipeline_id)
        e.pipeline_id, e.material_id, e.revision, e.branch,
        m.message, m.author, e.triggered_by, e.cause, e.pr_number
    FROM expanded e
    LEFT JOIN modifications m
        ON m.material_id = e.material_id AND m.revision = e.revision
    ORDER BY e.pipeline_id, e.material_id
)
SELECT pipeline_id, revision, branch, message, author, triggered_by, cause, pr_number
FROM joined
`

type LatestRunMetaByProjectSlugRow struct {
	PipelineID  pgtype.UUID
	Revision    string
	Branch      string
	Message     *string
	Author      *string
	TriggeredBy *string
	Cause       string
	PrNumber    int32
}

// Per-pipeline latest run with the triggering modification's
// commit metadata (branch, message, author, short revision). The
// runs.revisions JSONB is keyed by material_id; we unpack it and
// match each (material_id, revision) to the modification row
// that actually produced the run. LIMIT/DISTINCT ON at each level
// keeps the output one row per pipeline even when a run snapshots
// multiple materials — we pick the first match deterministically
// (order by material_id) so the card shows a stable ref.
func (q *Queries) LatestRunMetaByProjectSlug(ctx context.Context, slug string) ([]LatestRunMetaByProjectSlugRow, error) {
	rows, err := q.db.Query(ctx, latestRunMetaByProjectSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestRunMetaByProjectSlugRow{}
	for rows.Next() {
		var i LatestRunMetaByProjectSlugRow
		if err := rows.Scan(
			&i.PipelineID,
			&i.Revision,
			&i.Branch,
			&i.Message,
			&i.Author,
			&i.TriggeredBy,
			&i.Cause,
			&i.PrNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestRunMetaPerProject = `-- name: LatestRunMetaPerProject :many
WITH latest AS (
    SELECT DISTINCT ON (pl.project_id)
        pl.project_id, r.id AS run_id, r.revisions, r.triggered_by,
        r.cause, r.cause_detail
    FROM runs r
    JOIN pipelines pl ON pl.id = r.pipeline_id
    ORDER BY pl.project_id, r.created_at DESC
),
expanded AS (
    SELECT l.project_id,
           l.triggered_by,
           l.cause,
           -- Guard the JSON→int cast: only accept 1-9 digits so a
           -- malformed cause_detail (pr_number = "abc", a negative, or
           -- a value past int32) can't 500 the cards. 9 digits caps at
           -- 999,999,999 < int32 max; anything else falls back to 0.
           (CASE
               WHEN l.cause_detail->>'pr_number' ~ '^[0-9]{1,9}$'
               THEN (l.cause_detail->>'pr_number')::int
               ELSE 0
           END)::int AS pr_number,
           (key)::uuid AS material_id,
           (value->>'revision')::text AS revision,
           (value->>'branch')::text AS branch
    FROM latest l, jsonb_each(l.revisions)
),
joined AS (
    SELECT DISTINCT ON (e.project_id)
        e.project_id, e.revision, e.branch, m.message, m.author,
        e.triggered_by, e.cause, e.pr_number
    FROM expanded e
    LEFT JOIN modifications m
        ON m.material_id = e.material_id AND m.revision = e.revision
    ORDER BY e.project_id, e.material_id
)
SELECT project_id, revision, branch, message, author, triggered_by, cause, pr_number
FROM joined
`

type LatestRunMetaPerProjectRow struct {
	ProjectID   pgtype.UUID
	Revision    string
	Branch      string
	Message     *string
	Author      *string
	TriggeredBy *string
	Cause       string
	PrNumber    int32
}

// Per-project commit metadata from the most recent run across all
// of the project's pipelines. Same JSONB-expand pattern as the
// per-slug variant, just without the slug filter so one query
// serves the whole projects list. triggered_by is kept so the UI
// can fall back to the manual-trigger user when author is null
// (manual runs don't create webhook-driven modifications).
func (q *Queries) LatestRunMetaPerProject(ctx context.Context) ([]LatestRunMetaPerProjectRow, error) {
	rows, err := q.db.Query(ctx, latestRunMetaPerProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestRunMetaPerProjectRow{}
	for rows.Next() {
		var i LatestRunMetaPerProjectRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Revision,
			&i.Branch,
			&i.Message,
			&i.Author,
			&i.TriggeredBy,
			&i.Cause,
			&i.PrNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestRunPerPipelineByProjectSlug = `-- name: LatestRunPerPipelineByProjectSlug :many
SELECT DISTINCT ON (r.pipeline_id)
  r.pipeline_id, r.id, r.counter, r.cause, r.status,
  -- queue_reason: the pipeline card renders "Frozen: production" on a run held
  -- by an environment freeze (00078), same slot as cancel_reason.
  r.queue_reason,
  r.cancel_reason, r.superseded_by,
  r.created_at, r.started_at, r.finished_at, r.triggered_by,
  r.has_services, r.service_names
FROM runs r
JOIN pipelines pl ON pl.id = r.pipeline_id
JOIN projects p  ON p.id  = pl.project_id
WHERE p.slug = $1
ORDER BY r.pipeline_id, r.created_at DESC
`

type LatestRunPerPipelineByProjectSlugRow struct {
	PipelineID   pgtype.UUID
	ID           pgtype.UUID
	Counter      int64
	Cause        string
	Status       string
	QueueReason  *string
	CancelReason *string
	SupersededBy pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	TriggeredBy  *string
	HasServices  bool
	ServiceNames []string
}

// DISTINCT ON picks the most recent run per pipeline. Pipelines with
// no runs yet are absent from the result; the handler merges with
// ListPipelinesByProjectSlug to produce node entries.
//
// has_services comes from the snapshot stamped at run-create time
// (migration 00036) — lets the project page client skip the
// /api/v1/runs/:id/services fetch entirely on pipelines whose
// latest run never declared a `services:` block. Without it the
// project page issues one polling fetch per card. service_names
// (migration 00055) carries the names of those services so the card
// can label them without that fetch.
func (q *Queries) LatestRunPerPipelineByProjectSlug(ctx context.Context, slug string) ([]LatestRunPerPipelineByProjectSlugRow, error) {
	rows, err := q.db.Query(ctx, latestRunPerPipelineByProjectSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestRunPerPipelineByProjectSlugRow{}
	for rows.Next() {
		var i LatestRunPerPipelineByProjectSlugRow
		if err := rows.Scan(
			&i.PipelineID,
			&i.ID,
			&i.Counter,
			&i.Cause,
			&i.Status,
			&i.QueueReason,
			&i.CancelReason,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TriggeredBy,
			&i.HasServices,
			&i.ServiceNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobRunsByRunFull = `-- name: ListJobRunsByRunFull :many
SELECT id, stage_run_id, name, matrix_key, image,
       status, exit_code, error, started_at, finished_at, agent_id,
       cancel_requested_at, attempt,
       approval_gate, approvers, approval_description, approval_required,
       approval_quorum_label,
       awaiting_since, decided_by, decided_at, decision
FROM job_runs
WHERE run_id = $1
ORDER BY name, matrix_key NULLS FIRST
`

type ListJobRunsByRunFullRow struct {
	ID                  pgtype.UUID
	StageRunID          pgtype.UUID
	Name                string
	MatrixKey           *string
	Image               *string
	Status              string
	ExitCode            *int32
	Error               *string
	StartedAt           pgtype.Timestamptz
	FinishedAt          pgtype.Timestamptz
	AgentID             pgtype.UUID
	CancelRequestedAt   pgtype.Timestamptz
	Attempt             int32
	ApprovalGate        bool
	Approvers           []string
	ApprovalDescription *string
	ApprovalRequired    int32
	ApprovalQuorumLabel *string
	AwaitingSince       pgtype.Timestamptz
	DecidedBy           *string
	DecidedAt           pgtype.Timestamptz
	Decision            *string
}

func (q *Queries) ListJobRunsByRunFull(ctx context.Context, runID pgtype.UUID) ([]ListJobRunsByRunFullRow, error) {
	rows, err := q.db.Query(ctx, listJobRunsByRunFull, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobRunsByRunFullRow{}
	for rows.Next() {
		var i ListJobRunsByRunFullRow
		if err := rows.Scan(
			&i.ID,
			&i.StageRunID,
			&i.Name,
			&i.MatrixKey,
			&i.Image,
			&i.Status,
			&i.ExitCode,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.AgentID,
			&i.CancelRequestedAt,
			&i.Attempt,
			&i.ApprovalGate,
			&i.Approvers,
			&i.ApprovalDescription,
			&i.ApprovalRequired,
			&i.ApprovalQuorumLabel,
			&i.AwaitingSince,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Decision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobRunsForRuns = `-- name: ListJobRunsForRuns :many
SELECT run_id, stage_run_id, id, name, status, started_at, finished_at
FROM job_runs
WHERE run_id = ANY($1::uuid[])
ORDER BY run_id, stage_run_id, name
`

type ListJobRunsForRunsRow struct {
	RunID      pgtype.UUID
	StageRunID pgtype.UUID
	ID         pgtype.UUID
	Name       string
	Status     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

// Batch-loads job_runs for every run whose id is in the input
// array. The project detail page renders a GitLab-style pipeline
// flow per pipeline, each stage box listing its jobs — fetching
// these per pipeline would mean N queries. This single scan
// covers the card set.
func (q *Queries) ListJobRunsForRuns(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListJobRunsForRunsRow, error) {
	rows, err := q.db.Query(ctx, listJobRunsForRuns, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobRunsForRunsRow{}
	for rows.Next() {
		var i ListJobRunsForRunsRow
		if err := rows.Scan(
			&i.RunID,
			&i.StageRunID,
			&i.ID,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsByProjectSlug = `-- name: ListMaterialsByProjectSlug :many
SELECT m.pipeline_id, m.type, m.config, m.fingerprint
FROM materials m
JOIN pipelines pl ON pl.id = m.pipeline_id
JOIN projects p  ON p.id  = pl.project_id
WHERE p.slug = $1
ORDER BY m.pipeline_id, m.type
`

type ListMaterialsByProjectSlugRow struct {
	PipelineID  pgtype.UUID
	Type        string
	Config      []byte
	Fingerprint string
}

// All materials across pipelines of a project. VSM uses the
// `upstream` ones to build edges between pipeline nodes; git ones
// are informational (shown as entry points on the graph).
func (q *Queries) ListMaterialsByProjectSlug(ctx context.Context, slug string) ([]ListMaterialsByProjectSlugRow, error) {
	rows, err := q.db.Query(ctx, listMaterialsByProjectSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialsByProjectSlugRow{}
	for rows.Next() {
		var i ListMaterialsByProjectSlugRow
		if err := rows.Scan(
			&i.PipelineID,
			&i.Type,
			&i.Config,
			&i.Fingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByProjectSlug = `-- name: ListPipelinesByProjectSlug :many
SELECT pl.id, pl.name, pl.definition_version, pl.definition, pl.updated_at
FROM pipelines pl
JOIN projects p ON p.id = pl.project_id
WHERE p.slug = $1
ORDER BY pl.name
`

type ListPipelinesByProjectSlugRow struct {
	ID                pgtype.UUID
	Name              string
	DefinitionVersion int32
	Definition        []byte
	UpdatedAt         pgtype.Timestamptz
}

// Returns definition alongside metadata so the card can pull
// stage names from the YAML when the pipeline has never run
// (no stage_runs yet → no history to render from).
func (q *Queries) ListPipelinesByProjectSlug(ctx context.Context, slug string) ([]ListPipelinesByProjectSlugRow, error) {
	rows, err := q.db.Query(ctx, listPipelinesByProjectSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPipelinesByProjectSlugRow{}
	for rows.Next() {
		var i ListPipelinesByProjectSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefinitionVersion,
			&i.Definition,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsWithCounts = `-- name: ListProjectsWithCounts :many
WITH
latest_per_pipeline AS (
  SELECT DISTINCT ON (r.pipeline_id)
         r.pipeline_id, pl.project_id, r.status AS latest_status
  FROM runs r
  JOIN pipelines pl ON pl.id = r.pipeline_id
  ORDER BY r.pipeline_id, r.created_at DESC
),
project_health AS (
  SELECT project_id,
         bool_or(latest_status = 'running' OR latest_status = 'queued') AS any_running,
         bool_or(latest_status = 'failed') AS any_failed
  FROM latest_per_pipeline
  GROUP BY project_id
)
SELECT p.id, p.slug, p.name, p.description, p.config_path,
       p.created_at, p.updated_at,
       COALESCE(s.provider, '')::TEXT AS provider,
       COUNT(DISTINCT pl.id)::BIGINT AS pipeline_count,
       COUNT(r.id)::BIGINT AS run_count,
       MAX(r.created_at)::TIMESTAMPTZ AS latest_run_at,
       (
         CASE
           WHEN COUNT(DISTINCT pl.id) = 0 THEN 'no_pipelines'
           WHEN MAX(r.created_at) IS NULL THEN 'never_run'
           WHEN COALESCE(ph.any_running, false) THEN 'running'
           WHEN COALESCE(ph.any_failed, false) THEN 'failing'
           ELSE 'success'
         END
       )::TEXT AS status_agg
FROM projects p
LEFT JOIN pipelines pl ON pl.project_id = p.id
LEFT JOIN runs r ON r.pipeline_id = pl.id
LEFT JOIN scm_sources s ON s.project_id = p.id
LEFT JOIN project_health ph ON ph.project_id = p.id
GROUP BY p.id, s.provider, ph.any_running, ph.any_failed
ORDER BY p.updated_at DESC
`

type ListProjectsWithCountsRow struct {
	ID            pgtype.UUID
	Slug          string
	Name          string
	Description   *string
	ConfigPath    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Provider      string
	PipelineCount int64
	RunCount      int64
	LatestRunAt   pgtype.Timestamptz
	StatusAgg     string
}

// Project list used by the dashboard home. Joins enough aggregate info so the
// UI renders without round-tripping per row.
//
// Extra columns feed the card-style layout on /projects:
//   - provider: from the bound scm_source when present; empty string
//     when the project has no repo yet (shown as "—" in the UI).
//   - run_count: total runs across all pipelines — the card shows
//     "5 pipelines · 123 runs" as a density signal.
//   - status_agg: coarse health derived from the most recent run per
//     pipeline. Pre-computed in a CTE (latest_per_pipeline) so the
//     outer aggregate stays aggregate-only; correlated subqueries
//     inside CASE/WHEN during GROUP BY are fragile in Postgres and
//     blew up the previous version of this query.
func (q *Queries) ListProjectsWithCounts(ctx context.Context) ([]ListProjectsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listProjectsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsWithCountsRow{}
	for rows.Next() {
		var i ListProjectsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ConfigPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Provider,
			&i.PipelineCount,
			&i.RunCount,
			&i.LatestRunAt,
			&i.StatusAgg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSnapshotsForFreeze = `-- name: ListRunSnapshotsForFreeze :many
SELECT r.id AS run_id, r.definition
FROM runs r
JOIN pipelines pl ON pl.id = r.pipeline_id
WHERE pl.project_id = $1
  AND r.id = ANY($2::uuid[])
  AND r.definition <> '{}'::jsonb
`

type ListRunSnapshotsForFreezeParams struct {
	ProjectID pgtype.UUID
	RunIds    []pgtype.UUID
}

type ListRunSnapshotsForFreezeRow struct {
	RunID      pgtype.UUID
	Definition []byte
}

// Focused, project-scoped batch fetch of the IMMUTABLE run snapshots
// (runs.definition, migration 00067) for a handful of runs that have an
// awaiting_approval gate on the project-detail strip (#227). Run ONLY when at
// least one approval is waiting, so the common poll never pays it — unlike the
// shared LatestRun query (which also feeds VSM), this never touches the hot path.
// The pl.project_id predicate isolates by construction; '{}' (orphaned) snapshots
// are excluded so the caller falls back to "no badge".
func (q *Queries) ListRunSnapshotsForFreeze(ctx context.Context, arg ListRunSnapshotsForFreezeParams) ([]ListRunSnapshotsForFreezeRow, error) {
	rows, err := q.db.Query(ctx, listRunSnapshotsForFreeze, arg.ProjectID, arg.RunIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunSnapshotsForFreezeRow{}
	for rows.Next() {
		var i ListRunSnapshotsForFreezeRow
		if err := rows.Scan(&i.RunID, &i.Definition); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProjectSlug = `-- name: ListRunsByProjectSlug :many
SELECT r.id, r.pipeline_id, pl.name AS pipeline_name,
       r.counter, r.cause, r.status, r.queue_reason,
       r.cancel_reason, r.superseded_by, r.has_services, r.service_names,
       r.created_at, r.started_at, r.finished_at, r.triggered_by
FROM runs r
JOIN pipelines pl ON pl.id = r.pipeline_id
JOIN projects p ON p.id = pl.project_id
WHERE p.slug = $1
ORDER BY r.created_at DESC
LIMIT $2
`

type ListRunsByProjectSlugParams struct {
	Slug  string
	Limit int32
}

type ListRunsByProjectSlugRow struct {
	ID           pgtype.UUID
	PipelineID   pgtype.UUID
	PipelineName string
	Counter      int64
	Cause        string
	Status       string
	QueueReason  *string
	CancelReason *string
	SupersededBy pgtype.UUID
	HasServices  bool
	ServiceNames []string
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	TriggeredBy  *string
}

func (q *Queries) ListRunsByProjectSlug(ctx context.Context, arg ListRunsByProjectSlugParams) ([]ListRunsByProjectSlugRow, error) {
	rows, err := q.db.Query(ctx, listRunsByProjectSlug, arg.Slug, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsByProjectSlugRow{}
	for rows.Next() {
		var i ListRunsByProjectSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.PipelineName,
			&i.Counter,
			&i.Cause,
			&i.Status,
			&i.QueueReason,
			&i.CancelReason,
			&i.SupersededBy,
			&i.HasServices,
			&i.ServiceNames,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TriggeredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageRunsByRunOrdered = `-- name: ListStageRunsByRunOrdered :many
SELECT id, name, ordinal, status, started_at, finished_at
FROM stage_runs
WHERE run_id = $1
ORDER BY ordinal
`

type ListStageRunsByRunOrderedRow struct {
	ID         pgtype.UUID
	Name       string
	Ordinal    int32
	Status     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) ListStageRunsByRunOrdered(ctx context.Context, runID pgtype.UUID) ([]ListStageRunsByRunOrderedRow, error) {
	rows, err := q.db.Query(ctx, listStageRunsByRunOrdered, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStageRunsByRunOrderedRow{}
	for rows.Next() {
		var i ListStageRunsByRunOrderedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ordinal,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageRunsForRuns = `-- name: ListStageRunsForRuns :many
SELECT run_id, id, name, ordinal, status, started_at, finished_at
FROM stage_runs
WHERE run_id = ANY($1::uuid[])
ORDER BY run_id, ordinal
`

type ListStageRunsForRunsRow struct {
	RunID      pgtype.UUID
	ID         pgtype.UUID
	Name       string
	Ordinal    int32
	Status     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

// Batch-loads stage_runs for every run whose id is in the input
// array — the project detail page renders one pipeline card per
// pipeline and each card needs the latest run's stage states.
// Issuing one query per card would mean N+1 round trips; this
// amortizes them into a single scan.
func (q *Queries) ListStageRunsForRuns(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListStageRunsForRunsRow, error) {
	rows, err := q.db.Query(ctx, listStageRunsForRuns, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStageRunsForRunsRow{}
	for rows.Next() {
		var i ListStageRunsForRunsRow
		if err := rows.Scan(
			&i.RunID,
			&i.ID,
			&i.Name,
			&i.Ordinal,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopPipelinesPerProject = `-- name: ListTopPipelinesPerProject :many
SELECT pipeline_id, project_id, name, latest_run_id,
       latest_run_status, latest_run_at, definition
FROM (
  SELECT pl.id AS pipeline_id, pl.project_id, pl.name,
         pl.definition,
         -- COALESCE to empty string so sqlc types this as
         -- plain string (not *string). Empty means "never run" —
         -- the store layer treats "" the same way null would.
         COALESCE(lr.status, '')::TEXT AS latest_run_status,
         lr.created_at AS latest_run_at,
         -- Nil UUID when the LEFT JOIN LATERAL didn't match a run.
         -- Store-side treats that as "skip stage_runs lookup".
         COALESCE(lr.id, '00000000-0000-0000-0000-000000000000'::uuid) AS latest_run_id,
         ROW_NUMBER() OVER (
           PARTITION BY pl.project_id
           ORDER BY
             -- Failing pipelines first so the card headlines the
             -- problem state; then running, then anything else
             -- that has at least one run, ordered by recency;
             -- finally pipelines that never ran, alphabetical.
             -- Without this priority ladder, a project with 3
             -- freshly-applied-never-ran pipelines and 1 failing
             -- one would hide the failure behind "+N more".
             CASE lr.status
               WHEN 'failed' THEN 0
               WHEN 'running' THEN 1
               WHEN 'queued' THEN 2
               WHEN 'canceled' THEN 3
               WHEN 'success' THEN 4
               ELSE 5 -- never run
             END,
             lr.created_at DESC NULLS LAST,
             pl.name
         ) AS rn
  FROM pipelines pl
  LEFT JOIN LATERAL (
    SELECT id, status, created_at
    FROM runs
    WHERE pipeline_id = pl.id
    ORDER BY created_at DESC
    LIMIT 1
  ) lr ON true
) ranked
WHERE rn <= 20
ORDER BY project_id, rn
`

type ListTopPipelinesPerProjectRow struct {
	PipelineID      pgtype.UUID
	ProjectID       pgtype.UUID
	Name            string
	LatestRunID     pgtype.UUID
	LatestRunStatus string
	LatestRunAt     pgtype.Timestamptz
	Definition      []byte
}

// Per-project top-N (most recently updated) pipelines with their
// latest run status. Used to render the "mini stack" inside each
// project card without issuing one query per card (N+1). Capped at
// 20 entries per project via ROW_NUMBER partition — the side-by-
// side pipeline layout in the card fits comfortably up to ~10
// pipelines; projects beyond that surface a "+K more" hint. Bump
// the cap further if real-world projects regularly cross it.
//
// Also returns:
//   - latest_run_id: zero-UUID when the pipeline has never run.
//     Callers collect these to batch-load stage_runs.
//   - definition: the pipeline's YAML snapshot (JSONB). The card
//     renders grey "pending" stage pills from definition.Stages
//     when latest_run_id is zero, and reconciles definition vs.
//     stage_runs for mid-run/cancelled states.
func (q *Queries) ListTopPipelinesPerProject(ctx context.Context) ([]ListTopPipelinesPerProjectRow, error) {
	rows, err := q.db.Query(ctx, listTopPipelinesPerProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopPipelinesPerProjectRow{}
	for rows.Next() {
		var i ListTopPipelinesPerProjectRow
		if err := rows.Scan(
			&i.PipelineID,
			&i.ProjectID,
			&i.Name,
			&i.LatestRunID,
			&i.LatestRunStatus,
			&i.LatestRunAt,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pipelineMetricsByProjectSlug = `-- name: PipelineMetricsByProjectSlug :many
WITH per_run AS (
    SELECT r.id AS run_id, r.pipeline_id, r.status,
           EXTRACT(EPOCH FROM (r.finished_at - r.started_at))::double precision AS lead_s,
           COALESCE((
                SELECT SUM(EXTRACT(EPOCH FROM (sr.finished_at - sr.started_at)))
                FROM stage_runs sr
                WHERE sr.run_id = r.id
                  AND sr.finished_at IS NOT NULL AND sr.started_at IS NOT NULL
           ), 0)::double precision AS process_s
    FROM runs r
    JOIN pipelines pl ON pl.id = r.pipeline_id
    JOIN projects p ON p.id = pl.project_id
    WHERE p.slug = $1
      AND r.created_at >= now() - $2::interval
      AND r.status IN ('success','failed','canceled','skipped')
      AND r.started_at IS NOT NULL
      AND r.finished_at IS NOT NULL
)
SELECT pipeline_id,
       COUNT(*)::bigint AS runs_considered,
       COUNT(*) FILTER (WHERE status = 'success')::bigint AS passed,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_s), 0)::double precision AS lead_time_p50_s,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY process_s), 0)::double precision AS process_time_p50_s
FROM per_run
GROUP BY pipeline_id
`

type PipelineMetricsByProjectSlugParams struct {
	Slug        string
	SinceWindow pgtype.Interval
}

type PipelineMetricsByProjectSlugRow struct {
	PipelineID      pgtype.UUID
	RunsConsidered  int64
	Passed          int64
	LeadTimeP50S    float64
	ProcessTimeP50S float64
}

// Per-pipeline aggregate stats over the last $2 interval. Terminal
// runs only — queued/running are excluded so the medians don't move
// during active work. `process_time_p50_seconds` is the median of
// the per-run sum of stage_run durations (actual busy time),
// distinct from `lead_time_p50_seconds` (wall-clock run duration).
func (q *Queries) PipelineMetricsByProjectSlug(ctx context.Context, arg PipelineMetricsByProjectSlugParams) ([]PipelineMetricsByProjectSlugRow, error) {
	rows, err := q.db.Query(ctx, pipelineMetricsByProjectSlug, arg.Slug, arg.SinceWindow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineMetricsByProjectSlugRow{}
	for rows.Next() {
		var i PipelineMetricsByProjectSlugRow
		if err := rows.Scan(
			&i.PipelineID,
			&i.RunsConsidered,
			&i.Passed,
			&i.LeadTimeP50S,
			&i.ProcessTimeP50S,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pipelineStageMetricsByProjectSlug = `-- name: PipelineStageMetricsByProjectSlug :many
WITH recent_runs AS (
    SELECT pl.id AS pipeline_id, recent.id AS run_id
    FROM pipelines pl
    JOIN projects p ON p.id = pl.project_id
    CROSS JOIN LATERAL (
        SELECT r.id
        FROM runs r
        WHERE r.pipeline_id = pl.id
          AND r.status IN ('success','failed','canceled','skipped')
        -- idx_runs_pipeline_counter makes this ten index entries per pipeline,
        -- rather than a scan of cumulative run history.
        ORDER BY r.counter DESC
        LIMIT $2
    ) recent
    WHERE p.slug = $1
), scope AS (
    SELECT recent.pipeline_id, sr.name AS stage_name, sr.status AS stage_status,
           EXTRACT(EPOCH FROM (sr.finished_at - sr.started_at))::double precision AS duration_s
    FROM recent_runs recent
    JOIN stage_runs sr ON sr.run_id = recent.run_id
    WHERE sr.started_at IS NOT NULL
      AND sr.finished_at IS NOT NULL
      AND sr.status IN ('success','failed','canceled','skipped')
)
SELECT pipeline_id,
       stage_name,
       COUNT(*)::bigint AS runs_considered,
       COUNT(*) FILTER (WHERE stage_status = 'success')::bigint AS passed,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY duration_s), 0)::double precision AS duration_p50_s,
       COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY duration_s), 0)::double precision AS duration_p95_s
FROM scope
GROUP BY pipeline_id, stage_name
ORDER BY pipeline_id, stage_name
`

type PipelineStageMetricsByProjectSlugParams struct {
	Slug        string
	SampleLimit int32
}

type PipelineStageMetricsByProjectSlugRow struct {
	PipelineID     pgtype.UUID
	StageName      string
	RunsConsidered int64
	Passed         int64
	DurationP50S   float64
	DurationP95S   float64
}

// Per-stage aggregates over the latest N terminal builds for each pipeline.
// A conditional stage may therefore have fewer than N samples.
func (q *Queries) PipelineStageMetricsByProjectSlug(ctx context.Context, arg PipelineStageMetricsByProjectSlugParams) ([]PipelineStageMetricsByProjectSlugRow, error) {
	rows, err := q.db.Query(ctx, pipelineStageMetricsByProjectSlug, arg.Slug, arg.SampleLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineStageMetricsByProjectSlugRow{}
	for rows.Next() {
		var i PipelineStageMetricsByProjectSlugRow
		if err := rows.Scan(
			&i.PipelineID,
			&i.StageName,
			&i.RunsConsidered,
			&i.Passed,
			&i.DurationP50S,
			&i.DurationP95S,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMetricsAggregated = `-- name: ProjectMetricsAggregated :many
WITH per_run AS (
    SELECT pl.project_id, r.status,
           EXTRACT(EPOCH FROM (r.finished_at - r.started_at))::double precision AS lead_s,
           COALESCE((
                SELECT SUM(EXTRACT(EPOCH FROM (sr.finished_at - sr.started_at)))
                FROM stage_runs sr
                WHERE sr.run_id = r.id
                  AND sr.finished_at IS NOT NULL AND sr.started_at IS NOT NULL
           ), 0)::double precision AS process_s
    FROM runs r
    JOIN pipelines pl ON pl.id = r.pipeline_id
    WHERE r.created_at >= now() - $1::interval
      AND r.status IN ('success','failed','canceled','skipped')
      AND r.started_at IS NOT NULL
      AND r.finished_at IS NOT NULL
)
SELECT project_id,
       COUNT(*)::bigint AS runs_considered,
       COUNT(*) FILTER (WHERE status = 'success')::bigint AS passed,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_s), 0)::double precision AS lead_time_p50_s,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY process_s), 0)::double precision AS process_time_p50_s
FROM per_run
GROUP BY project_id
`

type ProjectMetricsAggregatedRow struct {
	ProjectID       pgtype.UUID
	RunsConsidered  int64
	Passed          int64
	LeadTimeP50S    float64
	ProcessTimeP50S float64
}

// Per-project roll-up of terminal runs over the last $1 interval.
// Same math as PipelineMetricsByProjectSlug but grouped by project
// instead of pipeline — the projects list card shows one KPI strip
// per project, so aggregating in SQL saves an N×round-trip dance
// when compared with looping the per-slug query per project.
func (q *Queries) ProjectMetricsAggregated(ctx context.Context, sinceWindow pgtype.Interval) ([]ProjectMetricsAggregatedRow, error) {
	rows, err := q.db.Query(ctx, projectMetricsAggregated, sinceWindow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMetricsAggregatedRow{}
	for rows.Next() {
		var i ProjectMetricsAggregatedRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.RunsConsidered,
			&i.Passed,
			&i.LeadTimeP50S,
			&i.ProcessTimeP50S,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tailLogLinesByJob = `-- name: TailLogLinesByJob :many
SELECT seq, stream, at, text
FROM (
    SELECT seq, stream, at, text
    FROM log_lines
    WHERE job_run_id = $1
    ORDER BY seq DESC
    LIMIT $2
) recent
ORDER BY seq
`

type TailLogLinesByJobParams struct {
	JobRunID pgtype.UUID
	Limit    int32
}

type TailLogLinesByJobRow struct {
	Seq    int64
	Stream string
	At     pgtype.Timestamptz
	Text   string
}

// Returns the tail (up to $2 lines) of a job's logs, oldest-first within the
// returned window, so the UI can append-only render.
func (q *Queries) TailLogLinesByJob(ctx context.Context, arg TailLogLinesByJobParams) ([]TailLogLinesByJobRow, error) {
	rows, err := q.db.Query(ctx, tailLogLinesByJob, arg.JobRunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TailLogLinesByJobRow{}
	for rows.Next() {
		var i TailLogLinesByJobRow
		if err := rows.Scan(
			&i.Seq,
			&i.Stream,
			&i.At,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vSMEdgeTimingByProjectSlug = `-- name: VSMEdgeTimingByProjectSlug :many
WITH pairs AS (
    SELECT
        up_pl.id AS from_pipeline_id,
        down_pl.id AS to_pipeline_id,
        EXTRACT(EPOCH FROM (down.started_at - up.finished_at))::double precision AS wait_s
    FROM runs down
    JOIN pipelines down_pl ON down_pl.id = down.pipeline_id
    JOIN projects p ON p.id = down_pl.project_id
    JOIN runs up ON up.id = (down.cause_detail->>'upstream_run_id')::uuid
    JOIN pipelines up_pl ON up_pl.id = up.pipeline_id
    WHERE p.slug = $1
      AND down.cause = 'upstream'
      AND down.cause_detail->>'upstream_run_id' IS NOT NULL
      AND down.started_at IS NOT NULL
      AND up.finished_at IS NOT NULL
      AND down.started_at >= up.finished_at
      AND down.created_at >= now() - $2::interval
)
SELECT from_pipeline_id, to_pipeline_id,
       COUNT(*)::bigint AS samples,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY wait_s), 0)::double precision AS wait_p50_s
FROM pairs
GROUP BY from_pipeline_id, to_pipeline_id
`

type VSMEdgeTimingByProjectSlugParams struct {
	Slug        string
	SinceWindow pgtype.Interval
}

type VSMEdgeTimingByProjectSlugRow struct {
	FromPipelineID pgtype.UUID
	ToPipelineID   pgtype.UUID
	Samples        int64
	WaitP50S       float64
}

// Median wait time per upstream→downstream edge in the project's
// VSM. Wait = downstream.started_at − upstream.finished_at, over
// terminal-or-dispatched runs where cause='upstream' and the
// cause_detail's upstream_run_id resolves to a real upstream run.
// Grouping by (from_pipeline_id, to_pipeline_id) so multiple edges
// from the same upstream to different downstreams each get their
// own median — the VSM graph labels arrows with these numbers.
func (q *Queries) VSMEdgeTimingByProjectSlug(ctx context.Context, arg VSMEdgeTimingByProjectSlugParams) ([]VSMEdgeTimingByProjectSlugRow, error) {
	rows, err := q.db.Query(ctx, vSMEdgeTimingByProjectSlug, arg.Slug, arg.SinceWindow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VSMEdgeTimingByProjectSlugRow{}
	for rows.Next() {
		var i VSMEdgeTimingByProjectSlugRow
		if err := rows.Scan(
			&i.FromPipelineID,
			&i.ToPipelineID,
			&i.Samples,
			&i.WaitP50S,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
